spring:
  application:
    name: member-service
  task:
    execution:
      pool:
        max-size: 160
  datasource:
    url: jdbc:mysql://localhost:3306/member_service
    username: root
    password: password
    hikari:
      maximum-pool-size: 150
      jdbc-url: jdbc:mysql://localhost:3306/member_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        dialect.storage_engine: innodb
  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/member_service
    user: root
    password: password

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        orm.jpa: debug
        transaction: debug
