DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS MEMBER_AUTHORITIES;

CREATE TABLE MEMBER (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB CHARSET=UTF8MB4;

CREATE TABLE MEMBER_AUTHORITIES (
    member_id BIGINT NOT NULL,
    authorities VARBINARY(255),
    FOREIGN KEY (member_id) REFERENCES MEMBER(id) ON UPDATE CASCADE
) ENGINE=INNODB CHARSET=UTF8MB4;